---
title: "Project Plan"
author: "Anne Braae"
date: "12/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Flight delays

## Context

#### Business intelligence and data-driven decision making

What insights can the business/organisation gain from your analysis and how will your analysis help the business/organisation make better decisions? 

This is a data-driven exploratory analysis to provide insight on the impact of weather on flight delay. Consideration will also be given to other factors such as time of flight, airline carrier, frequency of flights and departure airport.

The report will allow Newark airport to decide if it is worth investing in improving facilities to allow aircraft to take off in the types of weather which are most affecting departure delays. By considering other factors, the report will also show if there might be other areas which would benefit from investment which could also reduce flight delays.

#### Domain knowledge and the business context

Briefly describe the business/organisation and where your analysis fits within its aims/activity.

Newark Airport (or Newark Liberty International Airport) is one of the three major airports in the New York metropolitan area. 

Along with the other two major New York airports, John F. Kennedy International Airport and LaGardia Airport, Newark Airport is owned by the Port Authority of New York and New Jersey. The Port Authority owns 5 airports in total.

Recently, $2.7 billion was invested to build a new Terminal One to replace Terminal A at Newark Airport. Other parts of the redevelopment program are focused on increasing airfield paving, redesigning roadways and improving parking.

Reducing flight delays is important to ensure a high quality of service for the airport. The Bureau of Transportation Statistics (BTS) counts flights as delayed if they depart 15 minutes or later than their scheduled time. For the airport, knowing what the primary cause for delays is can advise the airport authority as to what measures it needs to invest most in. Improving infrastructure or improving facilities to deal with poor weather conditions.

An American study on 2007 flight data estimated that delayed flights has cost the US economy a total of nearly 33 billion dollars.

Flights may be delayed due to reasons within the air carrier's control such as maintenance or issues with staffing or crew or for reasons outside the air carrier's control such as extreme weather delay, national aviation system delay. Over a third of the main cost of delay is fuel costs. With the aviation industry focusing on improving sustainability reducing unnecessary fuel use is paramount.

Optimizing processes and efficiently using resources are key to reducing flight delays and airlines and airports are using data analytics to improve on-time performance.

sources: 
[Bureau of Transportation Statistics (BTC)](https://www.bts.gov/topics/airlines-and-airports/understanding-reporting-causes-flight-delays-and-cancellations)
[](https://centreforaviation.com/analysis/reports/the-cost-of-delays-late-flights-cost-us-economy-usd33-billion-39215)
[Port Authority](https://www.panynj.gov/airports/en/index.html)

## Data

#### Internal and external data sources

* Internal data sources (provided by Newark Airport):
 - Internal data from several CSV files. Details below: <br />
 
 | Filename       | Description                                                                                                                                                        |
|----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `flights.csv`  | Information on all flights per day for Newark, John F. Kennedy and LaGuardia airports. <br>Includes departure and arrival times, delay times, destination airports |
| `airports.csv` | Information on airports in the flights data including names, geocoordinates, altitude, <br>timezone, daylight savings.                                             |
| `airlines.csv` | Information on airline carrier code and airline carrier full name.                                                                                                 |
| `planes.csv`   | Information on planes in the flights data including year of make, type, model and cruising speed.                                                                  |
| `weather.csv`  | Information on weather for the three New York airports including temperature, wind measurements, <br>precipitation, visibility and time of the recording per hour. |

* External data sources:
- Additional weather data was sourced from [The National Centers for Environmental Information](https://www.ncei.noaa.gov/data/global-hourly/archive/csv/). This was also in csv format.
This data included measurements per day for temperature, precipitation, wind and snow.

#### Types of data

The data consists of categorical (ordinal), categorical (nominal), numeric (continuous), numeric (discrete) and datetime variables. Examples of each are as follows:

categorical (ordinal) - `year`, `month`, `weekday`
categorical (nominal) - `dest_airport`, `engine` (type of engine)
numeric (continuous) - `wind_speed`, `temperature`
numeric (discrete) - `seats`, `engines` (number of engines)


#### Data formats

What format did your data come in? E.g. all downloaded flat files (CSV) or any data from APIs, scraping etc.

#### Data quality and bias

Briefly describe the quality of the data and whether you have any reasons to suggest the data is biased e.g. only data from a specific demographic even though a broader demographic would be of interest to the organisation.

## Ethics

#### Ethical issues in data sourcing and extraction

Do you have any ethical concerns regarding the sourcing and extraction of your data? 

#### Ethical implications of business requirements

Are there any ethical implications of the business requirements?

## Analysis

#### Stages in the data analysis process

What were the main stages in your data analysis process?

#### Tools for data analysis

What were the main tools you used for your analysis?

#### Descriptive, diagnostic, predictive and prescriptive analysis

Please report under which of the below categories your analysis falls **and why** (can be more than one) 

::: {.emphasis}
**Descriptive Analytics** tells you what happened in the past.

**Diagnostic Analytics** helps you understand why something happened in the past.

**Predictive Analytics** predicts what is most likely to happen in the future.

**Prescriptive Analytics** recommends actions you can take to affect those outcomes.
:::


# PDA Outcomes

### Working with Data (J4Y6 35)

#### 1. Plan an analysis to provide business intelligence

-   1.1 Business intelligence and data-driven decision making
-   1.2 Domain knowledge and the business context
-   1.4 Internal and external data sources
-   1.5 Data quality
-   1.6 Stages in the data analysis process
-   1.7 Descriptive, diagnostic, predictive and prescriptive analysis
-   1.9 Ethical implications of business requirements
-   1.10 Tools for data analysis

#### 2. Extract data from a variety of sources

-   2.1 Tools for querying data sources
-   2.2 Types of data (categorical and numerical data and their sub-types)
-   2.3 Data formats
-   2.6 Data quality including data bias
-   2.7 Ethical issues in data sourcing and extraction

#### 4. Analyse data to provide business intelligence

-   4.7 Role of domain knowledge in interpreting analyses
